<a href="https://colab.research.google.com/github/Hasnien/ML-Learning-Roadmap/blob/main/c03_Pandas.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**Pandas is for structured/tubular data** \
Series is basically a one dimensional labeled array

In [1]:
import pandas as pd
ages = pd.Series([22,25,30,32])
print(ages)

0    22
1    25
2    30
3    32
dtype: int64

In [2]:
print(ages[0])
print(ages[2])

22
30

**Dataframe**

In [3]:
data = {
    "name" : ["Noor","Shahed","Ovi"],
    "age" : [28,29,30],
    "salary" : [30000,35000,500]
}
df = pd.DataFrame(data)
print(df)

     name  age  salary
0    Noor   28   30000
1  Shahed   29   35000
2     Ovi   30     500

In [4]:
print(df.columns)
print(df.index)
print(df.shape)

Index(['name', 'age', 'salary'], dtype='object')
RangeIndex(start=0, stop=3, step=1)
(3, 3)

In [5]:
print(df["age"])

0    28
1    29
2    30
Name: age, dtype: int64

In [6]:
print(df[["name","salary"]])

     name  salary
0    Noor   30000
1  Shahed   35000
2     Ovi     500

In [7]:
df["age"]

0    28
1    29
2    30
Name: age, dtype: int64

In [8]:
df[["age"]]

   age
0   28
1   29
2   30

In [9]:
print(df.iloc[0])

name       Noor
age          28
salary    30000
Name: 0, dtype: object

In [10]:
print(df.iloc[0:2])

     name  age  salary
0    Noor   28   30000
1  Shahed   29   35000

In [11]:
print(df.iloc[1,2])

35000

In [12]:
print(df.loc[0])

name       Noor
age          28
salary    30000
Name: 0, dtype: object

In [13]:
print(df.loc[0,"name"])

Noor

**inspecting a dataset**

In [14]:
df.head()

     name  age  salary
0    Noor   28   30000
1  Shahed   29   35000
2     Ovi   30     500

In [15]:
df.tail()

     name  age  salary
0    Noor   28   30000
1  Shahed   29   35000
2     Ovi   30     500

In [16]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3 entries, 0 to 2
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   name    3 non-null      object
 1   age     3 non-null      int64
 2   salary  3 non-null      int64
dtypes: int64(2), object(1)
memory usage: 204.0+ bytes

In [17]:
df.describe()

        age        salary
count   3.0      3.000000
mean   29.0  21833.333333
std     1.0  18643.586922
min    28.0    500.000000
25%    28.5  15250.000000
50%    29.0  30000.000000
75%    29.5  32500.000000
max    30.0  35000.000000

In [18]:
df.shape

(3, 3)

**filtering data**

In [19]:
result= df[df["age"]>29]
print(result)

  name  age  salary
2  Ovi   30     500

In [20]:
data_f = df[(df["age"]>28) & (df["salary"]>20000)]
print(data_f)

     name  age  salary
1  Shahed   29   35000

In [21]:
data_f1 = df[(df["age"]>29) | (df["salary"]<20000)]
print(data_f1)

  name  age  salary
2  Ovi   30     500

In [22]:
df["annual_salary"] = df["salary"] * 12
print(df)

     name  age  salary  annual_salary
0    Noor   28   30000         360000
1  Shahed   29   35000         420000
2     Ovi   30     500           6000

In [23]:
df["high_salary"] = df["salary"]>30000
df

     name  age  salary  annual_salary  high_salary
0    Noor   28   30000         360000        False
1  Shahed   29   35000         420000         True
2     Ovi   30     500           6000        False

In [24]:
from numpy import nan
chart = {
    "name" : ["A","B","C"],
    "age" : [21,nan,30],
    "salary" : [30000,35000,nan]
}
df_new = pd.DataFrame(chart)
df_new

  name   age   salary
0    A  21.0  30000.0
1    B   NaN  35000.0
2    C  30.0      NaN

In [25]:
print(df_new.isnull())

    name    age  salary
0  False  False   False
1  False   True   False
2  False  False    True

In [26]:
print(df_new.isnull().sum())

name      0
age       1
salary    1
dtype: int64

In [27]:
df_new= df_new.dropna()
df_new

  name   age   salary
0    A  21.0  30000.0

In [28]:
df_new["age"] = df_new["age"].fillna(df_new["age"].mean())
df_new

/tmp/ipykernel_2566/3658226717.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_new["age"] = df_new["age"].fillna(df_new["age"].mean())

  name   age   salary
0    A  21.0  30000.0

In [29]:
df.sort_values("age")

     name  age  salary  annual_salary  high_salary
0    Noor   28   30000         360000        False
1  Shahed   29   35000         420000         True
2     Ovi   30     500           6000        False

In [30]:
df.sort_values("age",ascending=False)

     name  age  salary  annual_salary  high_salary
2     Ovi   30     500           6000        False
1  Shahed   29   35000         420000         True
0    Noor   28   30000         360000        False

**Value Counts**

In [31]:
data = {
    "Name": ["Rahim", "Karim", "Sara", "John", "Aisha", "David"],
    "Age": [25, 32, 28, 22, 35, 29],
    "Salary": [30000, 55000, 45000, 25000, 70000, 48000],
    "Experience": [1, 5, 3, 0, 8, 4],
    "Purchased": ["No", "Yes", "Yes", "No", "Yes", "Yes"]
}

df = pd.DataFrame(data)
df

    Name  Age  Salary  Experience Purchased
0  Rahim   25   30000           1        No
1  Karim   32   55000           5       Yes
2   Sara   28   45000           3       Yes
3   John   22   25000           0        No
4  Aisha   35   70000           8       Yes
5  David   29   48000           4       Yes

In [32]:
print(df["Purchased"].value_counts())

Purchased
Yes    4
No     2
Name: count, dtype: int64

In [33]:
data = {
    "Department": ["IT", "IT", "HR", "HR", "Sales"],
    "Salary": [50000, 60000, 40000, 45000, 55000]
}

df = pd.DataFrame(data)

In [34]:
result = df.groupby("Department")["Salary"].mean()
result

Department
HR       42500.0
IT       55000.0
Sales    55000.0
Name: Salary, dtype: float64

**Mini project of pandas**

In [35]:
import pandas as pd

data = {
    "Name": ["Rahim", "Karim", "Sara", "John", "Aisha", "David"],
    "Age": [25, 32, 28, 22, 35, 29],
    "Salary": [30000, 55000, 45000, 25000, 70000, 48000],
    "Experience": [1, 5, 3, 0, 8, 4],
    "Purchased": ["No", "Yes", "Yes", "No", "Yes", "Yes"]
}

df = pd.DataFrame(data)

print(df)

    Name  Age  Salary  Experience Purchased
0  Rahim   25   30000           1        No
1  Karim   32   55000           5       Yes
2   Sara   28   45000           3       Yes
3   John   22   25000           0        No
4  Aisha   35   70000           8       Yes
5  David   29   48000           4       Yes

In [36]:
print(df.shape)
df.info()

(6, 5)
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6 entries, 0 to 5
Data columns (total 5 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Name        6 non-null      object
 1   Age         6 non-null      int64
 2   Salary      6 non-null      int64
 3   Experience  6 non-null      int64
 4   Purchased   6 non-null      object
dtypes: int64(3), object(2)
memory usage: 372.0+ bytes

In [37]:
#Display only:Name & Salary
print(df[["Name","Salary"]])

    Name  Salary
0  Rahim   30000
1  Karim   55000
2   Sara   45000
3   John   25000
4  Aisha   70000
5  David   48000

In [38]:
#Find people with salary > 40000.
print(df["Salary"]>40000)

#Find people with experience >= 4.
print(df["Experience"]>=4)

0    False
1     True
2     True
3    False
4     True
5     True
Name: Salary, dtype: bool
0    False
1     True
2    False
3    False
4     True
5     True
Name: Experience, dtype: bool

In [44]:
#annualsalary
df["annualSalary"] = df["Salary"]*12
print(df["annualSalary"])

0    360000
1    660000
2    540000
3    300000
4    840000
5    576000
Name: annualSalary, dtype: int64

In [51]:
#average salary,higest salary
print(df["Salary"].mean())
print(df["Salary"].max())

45500.0
70000

In [54]:
print(df["Purchased"].value_counts())

Purchased
Yes    4
No     2
Name: count, dtype: int64

In [55]:
print(df.groupby("Purchased")["Salary"].mean())

Purchased
No     27500.0
Yes    54500.0
Name: Salary, dtype: float64